version: '3'
services:
  golang:
    build:
      context: ./docker_files/go
    container_name: circleci_golang_sample_server
    volumes:
      - '.:/go/src/app'
    ports:
      - '8001:8080'
    tty: true
